services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "1337:1337"
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"

  db:
    image: mongo:6
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: bai10
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
