openapi: 3.0.0
info:
  title: INTERN_NGUYEN_HUU_DUC
  description: RESSTFUL API cho ứng dụng CMS
  version: 1.0.0
servers:
  - url: http://localhost:1337
    description: Server local
paths:

  /api/login:
    post:
      summary: Đăng nhập người dùng
      description: Xác thực người dùng và trả về token. Thiết lập cookie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ok"
                  userData:
                    $ref: '#/components/schemas/User'
                  refreshToken:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - "missing data!"
                      - "username or password not correct!"
                      - "your account has been deleted!"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong!"

  /api/register:
    post:
      summary: Đăng ký người dùng
      description: Tạo tài khoản người dùng mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Register success!"
                  userData:
                    $ref: '#/components/schemas/User'
        '400':
          description: Yêu cầu không hợp lệ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - "Missing required data!"
                      - "Phone invalid"
                      - "Email invalid"
                      - "Username already exists!"
                  received:
                    type: object
                    properties:
                      username:
                        type: string
                      password:
                        type: string
                      nickName:
                        type: string
                      phone:
                        type: string
                      email:
                        type: string
                      avatar:
                        type: string
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Something went wrong!"

  /api/user/getUserInforOwn:
    get:
      summary: Lấy thông tin người dùng hiện tại
      description: Trả về thông tin của người dùng đang đăng nhập, dựa trên token xác thực.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin người dùng được trả về thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Không được phép
          content:
            application/json:
              example:
                message: "Unauthorized"
        '404':
          description: Không tìm thấy người dùng
          content:
            application/json:
              example:
                message: "User not found"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              example:
                message: "Internal server error"

  /api/user/getListProduct:
    get:
      summary: Lấy danh sách sản phẩm
      description: Trả về danh sách tất cả các sản phẩm hiện có trong hệ thống.
      responses:
        '200':
          description: Lấy danh sách sản phẩm thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ok"
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong!"

  
  /api/user/getProductById/{productId}:
    get:
      summary: Lấy thông tin chi tiết sản phẩm theo ID
      description: Trả về thông tin chi tiết của một sản phẩm dựa trên `productId`.
      parameters:
        - name: productId
          in: path
          required: true
          description: ID của sản phẩm cần truy vấn
          schema:
            type: string
            example: "6869057d315b0cbd6dec3da9"
      responses:
        '200':
          description: Lấy thông tin sản phẩm thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ok"
                  product:
                    $ref: '#/components/schemas/Product'
        '400':
          description: Yêu cầu không hợp lệ hoặc không tìm thấy sản phẩm
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "not found product"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong!"
    
  /api/admin/getListUsers:
    get:
      summary: Lấy danh sách tất cả người dùng
      description: Trả về danh sách tất cả người dùng có trong hệ thống.
      responses:
        '200':
          description: Lấy danh sách người dùng thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong"

  /api/admin/deleteUserById:
    delete:
      summary: Xoá người dùng theo ID
      description: Xoá người dùng dựa trên `userId` gửi trong phần body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                  example: "60c72b2f9f1b2c001c8e4f5b"
      responses:
        '200':
          description: Xoá người dùng thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User deleted successfully"
        '400':
          description: Thiếu hoặc sai định dạng userId
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "userId invalid"
        '404':
          description: Không tìm thấy người dùng
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User not found"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong"


  /api/admin/deleteProductById:
    delete:
      summary: Xoá sản phẩm theo ID
      description: Xoá sản phẩm dựa trên `productId` gửi trong phần body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
              properties:
                productId:
                  type: string
                  example: "60c72b2f9f1b2c001c8e4f5a"
      responses:
        '200':
          description: Xoá sản phẩm thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product deleted successfully"
        '400':
          description: Thiếu hoặc sai định dạng productId
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "productId invalid"
        '404':
          description: Không tìm thấy sản phẩm
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product not found"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong"

  /api/admin/addNewProduct:
    post:
      summary: Thêm sản phẩm mới
      description: Tạo một sản phẩm mới với tên và giá sản phẩm.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productName
                - productPrice
              properties:
                productName:
                  type: string
                  example: "Iphone 16"
                productPrice:
                  type: number
                  example: 1499
      responses:
        '201':
          description: Thêm sản phẩm thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example:
                      _id: "60c72b2f9f1b2c001c8e4f5a"
                      productName: "Iphone 16"
                      productPrice: 1499
        '400':
          description: Thiếu dữ liệu hoặc sai định dạng
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "missing data"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong"


  /api/admin/updateProduct:
    put:
      summary: Cập nhật thông tin sản phẩm
      description: Cập nhật thông tin sản phẩm với ID, tên và giá sản phẩm.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
              properties:
                productId:
                  type: string
                  example: "60c72b2f9f1b2c001c8e4f5a"
                productName:
                  type: string
                  example: "Iphone 16 Pro"
                productPrice:
                  type: number
                  example: 1599
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example:
                      _id: "60c72b2f9f1b2c001c8e4f5a"
                      productName: "Iphone 16 Pro"
                      productPrice: 1599
        '400':
          description: productId không hợp lệ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "productId invalid"
        '404':
          description: Không tìm thấy sản phẩm
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product not found"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "have wrong"

  /api/page/listProducts:
    get:
      summary: Lấy danh sách sản phẩm theo phân trang
      description: Trả về danh sách sản phẩm dựa trên phân trang với các tham số pageIndex và perPage.
      parameters:
        - in: query
          name: pageIndex
          schema:
            type: integer
            minimum: 0
          required: true
          description: Chỉ số trang (bắt đầu từ 0)
        - in: query
          name: perPage
          schema:
            type: integer
            minimum: 1
          required: true
          description: Số lượng sản phẩm mỗi trang
      responses:
        '200':
          description: Danh sách sản phẩm
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ok"
                  productList:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '400':
          description: Thiếu hoặc sai dữ liệu đầu vào
          content:
            application/json:
              example:
                message: "missing data"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              example:
                message: "have wrong!"

  /api/page/searchProductByName:
    post:
      summary: Tìm kiếm sản phẩm theo tên
      description: Trả về danh sách sản phẩm có tên chứa chuỗi được cung cấp.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productName:
                  type: string
                  example: "iPhone"
      responses:
        '200':
          description: Danh sách sản phẩm phù hợp
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ok"
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '400':
          description: Dữ liệu đầu vào bị thiếu
          content:
            application/json:
              example:
                message: "missing data"
        '500':
          description: Lỗi server nội bộ
          content:
            application/json:
              example:
                message: "have wrong!"




components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: integer
        nickName:
          type: string
        username:
          type: string
        password:
          type: string


    UserFull:
      type: object
      properties:
        userId:
          type: integer
        nickName:
          type: string
        password:
          type: string
        isAdmin:
          type: boolean

    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        nickName:
          type: string
      required:
        - username
        - password
        - nickName

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token JWT để xác thực người dùng hoặc quản trị viên
  Product:
      type: object
      properties:
        id:
          type: string
          example: "prd_abc123"
        productName:
          type: string
          example: "iPhone 15 Pro Max"
        productPrice:
          type: number
          example: 199000
        normalizedProductName:
          type: string
          example: 'iphone15promax'